#!/usr/bin/env node

/**
 * Environment Setup Script for CRM/ERP Platform
 * This script helps set up environment variables for different deployment targets
 */

const fs = require('fs')
const path = require('path')

const environments = {
  development: {
    DATABASE_URL: 'file:./dev.db',
    NEXTAUTH_URL: 'http://localhost:3000',
    NEXTAUTH_SECRET: 'dev-secret-key-change-in-production'
  },
  production: {
    DATABASE_URL: 'mysql://username:password@host:port/database?sslaccept=strict',
    NEXTAUTH_URL: 'https://your-app.vercel.app',
    NEXTAUTH_SECRET: 'your-super-secret-key-here'
  },
  vercel: {
    DATABASE_URL: 'mysql://username:password@host:port/database?sslaccept=strict',
    NEXTAUTH_URL: 'https://your-app.vercel.app',
    NEXTAUTH_SECRET: 'your-super-secret-key-here'
  }
}

function createEnvFile(env, customVars = {}) {
  const baseVars = environments[env] || environments.development
  const allVars = { ...baseVars, ...customVars }

  const envContent = `# Environment: ${env.toUpperCase()}
# Generated by env-setup.js on ${new Date().toISOString()}

${Object.entries(allVars)
  .map(([key, value]) => `${key}="${value}"`)
  .join('\n')}

# Optional: Add your third-party service keys here
# STRIPE_SECRET_KEY=""
# TWILIO_ACCOUNT_SID=""
# TWILIO_AUTH_TOKEN=""
# TWILIO_PHONE_NUMBER=""
# GOOGLE_CLIENT_ID=""
# GOOGLE_CLIENT_SECRET=""
`

  const fileName = env === 'vercel' ? '.env.vercel' : '.env.local'
  const filePath = path.join(process.cwd(), fileName)

  fs.writeFileSync(filePath, envContent, 'utf8')
  console.log(`✅ Created ${fileName} for ${env} environment`)
  console.log(`📝 Edit ${fileName} with your actual values`)
}

function showUsage() {
  console.log(`
🚀 CRM/ERP Platform Environment Setup

Usage: node env-setup.js [environment] [options]

Environments:
  development  - Local development with SQLite
  production   - Production deployment with MySQL
  vercel       - Vercel-specific configuration

Options:
  --help, -h   Show this help message

Examples:
  node env-setup.js development
  node env-setup.js production
  node env-setup.js vercel

For Vercel deployment:
1. Run: node env-setup.js vercel
2. Copy contents of .env.vercel to Vercel dashboard
3. Update DATABASE_URL with your PlanetScale connection string
`)
}

function main() {
  const args = process.argv.slice(2)
  const env = args[0]

  if (!env || env === '--help' || env === '-h') {
    showUsage()
    return
  }

  if (!environments[env]) {
    console.error(`❌ Unknown environment: ${env}`)
    console.log('Available environments:', Object.keys(environments).join(', '))
    return
  }

  console.log(`🔧 Setting up environment for: ${env}`)
  createEnvFile(env)

  if (env === 'vercel') {
    console.log(`
📋 Next steps for Vercel deployment:
1. Copy the contents of .env.vercel
2. Go to your Vercel project dashboard
3. Navigate to Settings → Environment Variables
4. Add each variable from .env.vercel
5. Update DATABASE_URL with your PlanetScale connection string
6. Redeploy your application
`)
  } else if (env === 'production') {
    console.log(`
📋 Next steps for production deployment:
1. Update DATABASE_URL with your MySQL connection string
2. Configure NEXTAUTH_URL with your domain
3. Generate a secure NEXTAUTH_SECRET
4. Add third-party service keys as needed
`)
  } else {
    console.log(`
📋 Next steps for development:
1. Run: npm run db:generate
2. Run: npm run db:migrate
3. Run: npm run dev
`)
  }
}

if (require.main === module) {
  main()
}

module.exports = { createEnvFile, environments }